### ISSUE TITLE
[CRITICAL ERROR] [Report] Software update reports dependency errors

### ISSUE THREAD

**Issue by Jason300** [holoiso-eol/holoiso#577] opened 2022-10-31 09:51 UTC
## Your Issue:
```
The reason why I tried to reinstall Holo in the first place, was because the Update through strange errors and soped me from updating anything

solving it from the command line showed that a package missmatch was present with a package "... freefdr" something

later on, the unupdatable softawre grew to more than 500
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
latest version
```

## Have you updated your installation recently?
```
at that time i had the newest version
```

**Comment by jahu00** [comment] 2022-11-03 18:55
I think this is caused by the latest SteamOS update being broken on holoiso. Updating from game mode will partially succeed. If you go to the desktop mode after that, you will get this state with many updates in the discover store that are dependency locked. You can try manually resolving those dependences (update packages in the right order) through the discover store, but it's a slow and tedious process. In my case, the discover store eventually broke and I was no longer able to start it (even after restarting SteamOS). Alternatively, you can go back to the game mode and retry the failed update. Each time more packages will get updated. There is a catch however. There is a Vulcan update that breaks holoiso and if it gets installed, SteamOS will great you with a black screen. Another issue report has an explanation on how to recover from this (and downgrade Vulcan).

**Closed as completed** 2023-09-08 08:03 UTC
