### ISSUE TITLE
[Report] Wrong screen aspect ratio when connected to external display with Anbernic win600

### ISSUE THREAD

**Issue by cheungyau2022** [holoiso-eol/holoiso#488] opened 2022-09-01 02:42 UTC
## Your Issue:
When connected to external display via Type-c to HDMI, there is black bars on both the left and right sides of the screen, looks like a 3:2 resolution while both my device's internal display and the connected monitor are 16:9 screens.

The only solution is to restart the device while connected to the external display. Then the video output would be behaving normally.

But once I disconnect the cable and reconnect again, I have to restart the device for the video output to display a 16:9 image.

**Comment by theVakhovskeIsTaken** [comment] 2022-09-02 15:05
Known issue, will be fixed in future updates.

**Comment by alphonsez1** [comment] 2022-09-04 01:29
I have a similar issue on my device. I'm not sure whether it's the same root cause.

I have a walk around that works for me by modifying `/usr/bin/gamescope-session` and replacing the line
`-w 1280 -h 800 \` 
with 
`-w 1280 -h 720 \`
It appears to fix the issue on my device.

Both my device and the external display are 16:9, so I'm not sure whether it will cause some issue when connecting to a display with a different aspect ratio.

**Comment by cheungyau2022** [comment] 2022-09-04 03:26
> I have a similar issue on my device. I'm not sure whether it's the same root cause.
> 
> I have a walk around that works for me by modifying `/usr/bin/gamescope-session` and replacing the line `-w 1280 -h 800 \` with `-w 1280 -h 720 \` It appears to fix the issue on my device.
> 
> Both my device and the external display are 16:9, so I'm not sure whether it will cause some issue when connecting to a display with a different aspect ratio.

Wow it works! Thanks so much.

**Comment by theVakhovskeIsTaken** [comment] 2022-09-04 15:25
Can reproduce this on my Win600 with 3050e, confirmed MESA issue with upstream 22.3 version, an downgrade will be available later.

**Comment by theVakhovskeIsTaken** [comment] 2022-09-04 23:48
Fixed as per latest update.

**Closed as completed by theVakhovskeIsTaken** 2022-09-04 23:48 UTC

**Comment by VGON7** [comment] 2022-09-20 11:32
> I have a similar issue on my device. I'm not sure whether it's the same root cause.
> 
> I have a walk around that works for me by modifying `/usr/bin/gamescope-session` and replacing the line `-w 1280 -h 800 \` with `-w 1280 -h 720 \` It appears to fix the issue on my device.
> 
> Both my device and the external display are 16:9, so I'm not sure whether it will cause some issue when connecting to a display with a different aspect ratio.

Hi,After I modified it and saved it, it reminded me to enter the password. I entered the password, but it said it was wrong. I did not enter it wrong. I don’t know why.
