### ISSUE TITLE
[Intermittent issue] Stuck on "Validating Installation" Screen

### ISSUE THREAD

**Issue by Salad360** [holoiso-eol/holoiso#606] opened 2022-11-18 17:18 UTC
Specs:
Intel Core i5-4690k
16GB DDR3 RAM
AMD Radeon RX570 8GB
Boot Drive: 7200RPM HDD

When booting into HoloISO, about 50% of the time it will boot into Gamemode UI with no issues. The other 50% of the time it will get stuck the "Validating Installation Screen" forever. The little melody that plays when booted into gamemode will play in the background when this happens but no matter how long I wait it will never get past this screen until I reboot. 

This issue will also trigger when switching to gamemode from desktop mode, only I get met with a black screen instead of the "validating instillation" screen.

I have made sure I'm up-to-date by running pacman -Syu

**Comment by theVakhovskeIsTaken** [comment] 2022-11-18 17:20
> Specs:
> Intel Core i5-4690k
> 16GB DDR3 RAM
> AMD Radeon RX570 8GB
> Boot Drive: 7200RPM HDD
> 
> 
> When booting into HoloISO, about 50% of the time it will boot into Gamemode UI with no issues. The other 50% of the time it will get stuck the "Validating Installation Screen" forever. The little melody that plays when booted into gamemode will play in the background when this happens but no matter how long I wait it will never get past this screen until I reboot. 
> 
> This issue will also trigger when switching to gamemode from desktop mode, only I get met with a black screen instead of the "validating instillation" screen.
> 
> I have made sure I'm up-to-date by running pacman -Syu

Let's get things straight:

Is your HDMI connected to the dGPU itself, just to make sure it is?

Have you tried to disable iGPU in BIOS?

**Comment by sciroccogti82** [comment] 2022-11-18 17:36
Same issue here alltho for me its 100% of the time. If I reinstall its fine until I update the system, then its the same error again. Also tried chimeraos it has the exact same bug, its like the newest stable update is doing it.

**Comment by Salad360** [comment] 2022-11-18 17:36
Yes and Yes

**Comment by Salad360** [comment] 2022-11-18 17:37
> > Specs:
> > Intel Core i5-4690k
> > 16GB DDR3 RAM
> > AMD Radeon RX570 8GB
> > Boot Drive: 7200RPM HDD
> > When booting into HoloISO, about 50% of the time it will boot into Gamemode UI with no issues. The other 50% of the time it will get stuck the "Validating Installation Screen" forever. The little melody that plays when booted into gamemode will play in the background when this happens but no matter how long I wait it will never get past this screen until I reboot.
> > This issue will also trigger when switching to gamemode from desktop mode, only I get met with a black screen instead of the "validating instillation" screen.
> > I have made sure I'm up-to-date by running pacman -Syu
> 
> Let's get things straight:
> 
> Is your HDMI connected to the dGPU itself, just to make sure it is?
> 
> Have you tried to disable iGPU in BIOS?

Yes and Yes

**Comment by theVakhovskeIsTaken** [comment] 2022-11-18 17:57
> > > Specs:
> > > Intel Core i5-4690k
> > > 16GB DDR3 RAM
> > > AMD Radeon RX570 8GB
> > > Boot Drive: 7200RPM HDD
> > > When booting into HoloISO, about 50% of the time it will boot into Gamemode UI with no issues. The other 50% of the time it will get stuck the "Validating Installation Screen" forever. The little melody that plays when booted into gamemode will play in the background when this happens but no matter how long I wait it will never get past this screen until I reboot.
> > > This issue will also trigger when switching to gamemode from desktop mode, only I get met with a black screen instead of the "validating instillation" screen.
> > > I have made sure I'm up-to-date by running pacman -Syu
> > 
> > Let's get things straight:
> > 
> > Is your HDMI connected to the dGPU itself, just to make sure it is?
> > 
> > Have you tried to disable iGPU in BIOS?
> 
> Yes and Yes

Aight, do one thing: press CTRL + Alt + F3, log-in under your credentials, type steamos-session-select plasma-x11-stable or plasma-persistent depending on what version you've got and log-in to your steam account

**Comment by Insperatus** [comment] 2022-11-18 18:48
This is also happening to me, stuck on Validating Installation, hear the initialization chime in the background, but it never gives me the UI. Happens 100% of the time. Seemed to be working fine before the latest update. 

Win Max 2
AMD R7-6800U
AMD Radeon 680m
32GB LPDDR5-6400
Boot Drive: WD_BLACK SN770 2TB NVMe
snapshot20221112.1354

I have made sure I'm up-to-date by running pacman -Syu

Disabling iGPU seems to make no difference.

> Aight, do one thing: press CTRL + Alt + F3, log-in under your credentials, type steamos-session-select plasma-x11-stable or plasma-persistent depending on what version you've got and log-in to your steam account

These commands return: `Unrecognized session 'plama-persistant'`  or `Unrecognized session 'plama-x11-stable'`

**Comment by JavaMR-HTML** [comment] 2022-11-18 23:51
I have the same issue, but it comes with an odd graphical glitch.

I'll paste the bug report forum below.

## Your Issue:
```
Boot gets stuck on a bugged "Verifying installation" screen. Boot sound plays, but no response from the system. Recovery mode works as intended.
```

## Your device's full specs
```
CPU: Intel Core i3
GPU: Low-end Intel Graphics, exact card unknown
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221101.1327
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
(attempted in recovery mode)

> Making Gamescope Mode Save file at "/root/.config/gamescope/modes.cfg"

> touch: cannot touch '/root/.steam/root/config/SteamAppData.vdf': No such file or directory

> 

```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by Salad360** [comment] 2022-11-19 01:50
> 

Both of those commands return “unrecognized session”

**Comment by theVakhovskeIsTaken** [comment] 2022-11-19 13:26
> This is also happening to me, stuck on Validating Installation, hear the initialization chime in the background, but it never gives me the UI. Happens 100% of the time. Seemed to be working fine before the latest update.
> 
> Win Max 2 AMD R7-6800U AMD Radeon 680m 32GB LPDDR5-6400 Boot Drive: WD_BLACK SN770 2TB NVMe snapshot20221112.1354
> 
> I have made sure I'm up-to-date by running pacman -Syu
> 
> Disabling iGPU seems to make no difference.
> 
> > Aight, do one thing: press CTRL + Alt + F3, log-in under your credentials, type steamos-session-select plasma-x11-stable or plasma-persistent depending on what version you've got and log-in to your steam account
> 
> These commands return: `Unrecognized session 'plama-persistant'` or `Unrecognized session 'plama-x11-stable'`

Looks like Valve deliberately broke something... I'll take a look later

**Comment by AaronBaird1** [comment] 2022-11-19 17:42
@theVakhovskeIsTaken 
Typing `steamos-session-select plasma` returns:

`Updated user selected session to plasma-steamos-oneshot.desktop`
`Updated user selected session to plasma-steamos-oneshot.desktop`
`Updated system autologin session to plasma-steamos-oneshot.desktop`
`Restarted SDDM`

rebooting afterwards will take you straight into plasma desktop

**Comment by Ganju0** [comment] 2022-11-19 21:01
> This is also happening to me, stuck on Validating Installation, hear the initialization chime in the background, but it never gives me the UI. Happens 100% of the time. Seemed to be working fine before the latest update.
> 
> Win Max 2 AMD R7-6800U AMD Radeon 680m 32GB LPDDR5-6400 Boot Drive: WD_BLACK SN770 2TB NVMe snapshot20221112.1354
> 
> I have made sure I'm up-to-date by running pacman -Syu
> 
> Disabling iGPU seems to make no difference.
> 
> > Aight, do one thing: press CTRL + Alt + F3, log-in under your credentials, type steamos-session-select plasma-x11-stable or plasma-persistent depending on what version you've got and log-in to your steam account
> 
> These commands return: `Unrecognized session 'plama-persistant'` or `Unrecognized session 'plama-x11-stable'`

Throwing my 2 cents in to say I did a fresh install on my win max 2, updated, and got stuck on reboot at "starting session". I rebooted and now stuck on "validating install"

**Comment by configari** [comment] 2022-11-20 08:57
Same issue here, I tried the offline install and got the same result. Will installing steamOS holo normally (3.1) give the error?

**Comment by Salad360** [comment] 2022-11-20 16:22
> 

So installed a 2nd HDD in my system as I was running out of space on the first one and after I added the 2nd drive to my /etc/fstab and rebooted I noticed that this issue started happening 100% of the time. I dropped to a terminal session and removed the word “realtime” from my 2nd drive’s entry and I was able to boot with 50% success again. I will try removing “realtime” from my boot drive’s entry and see if that solves the problem 100%

**Comment by Salad360** [comment] 2022-11-20 17:32
> > 
> 
> So installed a 2nd HDD in my system as I was running out of space on the first one and after I added the 2nd drive to my /etc/fstab and rebooted I noticed that this issue started happening 100% of the time. I dropped to a terminal session and removed the word “realtime” from my 2nd drive’s entry and I was able to boot with 50% success again. I will try removing “realtime” from my boot drive’s entry and see if that solves the problem 100%

Nope, that didn't fix it.

**Comment by sciroccogti82** [comment] 2022-11-20 19:20
For me this problem got fixed by never setting resolution and refresh manually, leaving it on auto. I loose 120hz tho sadly.

**Comment by Ganju0** [comment] 2022-11-20 20:04
> For me this problem got fixed by never setting resolution and refresh manually, leaving it on auto. I loose 120hz tho sadly.

Huh. Well this got me thinking and I plugged my gpd win max 2 into a monitor and then turned it on and it booted to the monitor. I then unplugged and was able to use it like normal. I rebooted and got the start up chime but a black screen. Plugged it into the monitor again and it popped up. I unplugged it and it works now. So every time I reboot I have to plug into a monitor

**Comment by configari** [comment] 2022-11-20 20:31
> For me this problem got fixed by never setting resolution and refresh manually, leaving it on auto. I loose 120hz tho sadly.

How can I make it so itll set the resolution automatically & fix the issue temporarily?

**Comment by Salad360** [comment] 2022-11-21 16:32
> For me this problem got fixed by never setting resolution and refresh manually, leaving it on auto. I loose 120hz tho sadly.

I discovered the same thing last night, I had been manually setting the output to 2k120 Instead of 4k60 which it defaults to. Auto lets me switch between desktop and game mode again and not have to reboot all the time. Bummer I don’t get 120hz tho.

**Comment by AaronBaird1** [comment] 2022-11-21 17:44
> > For me this problem got fixed by never setting resolution and refresh manually, leaving it on auto. I loose 120hz tho sadly.
> 
> Huh. Well this got me thinking and I plugged my gpd win max 2 into a monitor and then turned it on and it booted to the monitor. I then unplugged and was able to use it like normal. I rebooted and got the start up chime but a black screen. Plugged it into the monitor again and it popped up. I unplugged it and it works now. So every time I reboot I have to plug into a monitor

WM2 here too.  So it seems like a problem with the built in display.  maybe resolution? Bios setting?

**Comment by schusterro** [comment] 2022-11-22 18:56
HoloISO is a 100% disaster on the Win Max 2 with ADM 6800U. First, I could barely boot it, but with a TV attached I could enter game mode at last. But when I entered desktop mode, the Steam client crashed and so I restarted the device. Since then, it doesn't boot anymore and stays with the "Verifying installation" screen on the laptop. The TV output remains blank.

The "latest" ISO, referenced on the project's home page (https://github.com/bhaiest/holoiso/releases/latest), cannot be downloaded (HTTP 404), si I tried the really latest from nov 8: https://gdrivecdn.thevakhovske.pw/3:/HoloISO/HoloISO_Stable_OfflineInstaller-20221106_1516-x86_64.iso

When trying to install along Windows 11, it just installs on the partition but doesn't modify the bootloader or install grub on it, so it cannot be booted.
When selecting to install on the whole drive, after setting up the Wifi it installs an update but then gets stuck on "Verifying installation". The SteamOS startup sound can be heard in the background but it still gets stuck on that Verify screen.

Edit:
These commands after CTRL-ALT-F3:
steamos-session-select plasma
shutdown now

Helped. Took me into desktop mode after restart, and after 10 more restarts with pluggin/unplugging the HDMI cable it now boots into game mode. Half of the time, BT doesn work, and then a restart remedies the problem. Also I will stay away from desktop mode from now on because it messes up everything.

**Comment by tazket** [comment] 2022-12-03 12:28
> > For me this problem got fixed by never setting resolution and refresh manually, leaving it on auto. I loose 120hz tho sadly.
> 
> Huh. Well this got me thinking and I plugged my gpd win max 2 into a monitor and then turned it on and it booted to the monitor. I then unplugged and was able to use it like normal. I rebooted and got the start up chime but a black screen. Plugged it into the monitor again and it popped up. I unplugged it and it works now. So every time I reboot I have to plug into a monitor

Also WM2, same situation. It also goes black when switching back from desktop mode. Requires a monitor switch to make it work. Using a fake HDMI dongle as workaround for now.

**Comment by GKMoritz** [comment] 2022-12-20 17:19
The problem seems to be fixed with Version 4.1, at least if you boot into Plasma first and then use the "back to gamemode" button.

Tested on 
Intel NUC6i7KYK
Intel Core 7-6770HQ
Intel Iris Pro 580
(has the issue since the first offline installer)

**Comment by Livins1** [comment] 2022-12-26 03:18
This might be caused by the gamescope option to set specific resolution, I found every time after change that option, I will get "Verifying installation", and it will never get into gamescope.

Try this When you get "Verifying installation":
**CTRL+ALT+F3**   //make yourself a terminal, sometimes press CTRL+ALT+F4,  then, CTRL+ALT+F3 or F2.
//  i am not actually sure here, maybe someone running game-scope in root user ?
**Login into user/root account**  
// find mode.cfg 
**cd ~/.config/gamescope/**
// you can see there is a file named modes.cfg
// clean it, not remove it.
**rm modes.cfg && touch modes.cfg**
**reboot**
// this solves my problem

**Comment by nonobio** [comment] 2023-05-03 10:22
Hi,

I don't know if there is anything related to [my issue with SteamOS 2](https://github.com/ValveSoftware/SteamOS/issues/995) but if there is, I'll be happy to have your advice about it :)

**Closed as completed** 2023-09-08 08:02 UTC
