### ISSUE TITLE
[FAILED] Failed to start Jupiter BIOS Update Service

### ISSUE THREAD

**Issue by Timmyval123** [holoiso-eol/holoiso#198] opened 2022-05-26 09:18 UTC
after installing, when attempting to boot I get this message no matter what. I am Running a R5 3600, 5700xt, ASrock B450m Pro4. Tried updating BIOS, no effect. Any ideas on how to fix this ?

**Comment by theVakhovskeIsTaken** [comment] 2022-05-26 09:21
> after installing, when attempting to boot I get this message no matter what. I am Running a R5 3600, 5700xt, ASrock B450m Pro4. Tried updating BIOS, no effect. Any ideas on how to fix this ?

Sure. Let's get this debugged. Can you reboot to Recovery mode under `advanced options for SteamOS`?

**Comment by Timmyval123** [comment] 2022-05-26 09:29
> > after installing, when attempting to boot I get this message no matter what. I am Running a R5 3600, 5700xt, ASrock B450m Pro4. Tried updating BIOS, no effect. Any ideas on how to fix this ?
> 
> Sure. Let's get this debugged. Can you reboot to Recovery mode under `advanced options for SteamOS`?


Yes I am able to boot into recovery mode

**Comment by theVakhovskeIsTaken** [comment] 2022-05-26 09:30
> > > after installing, when attempting to boot I get this message no matter what. I am Running a R5 3600, 5700xt, ASrock B450m Pro4. Tried updating BIOS, no effect. Any ideas on how to fix this ?
> > 
> > Sure. Let's get this debugged. Can you reboot to Recovery mode under `advanced options for SteamOS`?
> 
> 
> Yes I am able to boot into recovery mode 
> 
> 

Good. Type `holoiso-disable-sessions` in, and boot to Plasma (X11).

**Comment by Timmyval123** [comment] 2022-05-26 11:58
Ok, its flashes the same Failure screen but then boots into a login screen. But I am unable to select a user as prompted

**Comment by CooperRecob** [comment] 2022-05-26 12:24
I was able to get in after doing that as well

**Comment by Timmyval123** [comment] 2022-05-26 12:26
> I was able to get in after doing that as well

Were you able to select User and enter password? I am unable to do so

**Comment by CooperRecob** [comment] 2022-05-26 12:41
> > I was able to get in after doing that as well
> 
> 
> 
> Were you able to select User and enter password? I am unable to do so

You have to select plasma at the top left of your screen then you should be able to get in, that is where I am stuck. Cant get into the actual steamos ui

**Comment by SirTZN** [comment] 2022-05-26 22:16
I appear to also be having this issue.
GPU: Nvidia RTX 2070 super

I installed the latest release, ran the installer with NVIDIA selected, and I get the same error mentioned (can't update Jupiter or whatever). I got this same error before today's release when I manually installed the 515 driver myself. 

I've tried making the USB in DD mode, installing it on a hard drive, installing it on a SSD, installing it on an SSD connected through a USB cable, same issue each time. I had success on an Intel laptop with the Mesa downgrade but that's all I could get working.

I ran "holoiso-disable-sessions" and that got me into the desktop as expected, but it'll only let me run in x11 not gamescope.

If it would be of any help I have a GTX 1080 laying around I could try out.

**Comment by mooock** [comment] 2022-05-26 22:19
Same problem here, I have a Skylake i9-7900X + RTX 3090. Tried all boot combinations

**Comment by theVakhovskeIsTaken** [comment] 2022-05-26 22:20
NVIDIA users:

Edit /boot/grub/grub.cfg and add `nvidia-drm.modeset=1` after splash

**Comment by Timmyval123** [comment] 2022-05-26 22:35
> > > > after installing, when attempting to boot I get this message no matter what. I am Running a R5 3600, 5700xt, ASrock B450m Pro4. Tried updating BIOS, no effect. Any ideas on how to fix this ?
> > > 
> > > 
> > > Sure. Let's get this debugged. Can you reboot to Recovery mode under `advanced options for SteamOS`?
> > 
> > 
> > Yes I am able to boot into recovery mode
> 
> Good. Type `holoiso-disable-sessions` in, and boot to Plasma (X11).

Ok, I'm able to get into a boot screen where I can select plasma in the top right. However I am unable to do anything further. It says to select user and password but I am unable to do so. My mouse cursor works but I can click anything.

**Comment by SirTZN** [comment] 2022-05-26 22:46
> NVIDIA users:
> 
> Edit /boot/grub/grub.cfg and add `nvidia-drm.modeset=1` after splash

I'm not sure exactly what you mean here. I tried adding it at the beginning and end of the file and nothing changed. Is there a specific part I have to put it?

Thanks!

**Comment by mooock** [comment] 2022-05-26 22:58
> 
Started in recovery mode

cd /boot/grub
vim grub.cfg 

Editor:
?splash
added "nvidia-drm.modeset=1"
?!x

Rebooted still with same error

![image](https://user-images.githubusercontent.com/1118931/170592511-56bd659f-75b8-4062-9f5c-32d8f9b40ff8.png)
![image](https://user-images.githubusercontent.com/1118931/170592632-56a70216-6b8b-48bd-98ed-57595928b6e1.png)

**Comment by CooperRecob** [comment] 2022-05-26 23:26
> > 
> 
> Started in recovery mode
> 
> 
> 
> cd /boot/grub
> 
> vim grub.cfg 
> 
> 
> 
> Editor:
> 
> ?splash
> 
> added "nvidia-drm.modeset=1"
> 
> ?!x
> 
> 
> 
> Rebooted still with same error
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1118931/170592511-56bd659f-75b8-4062-9f5c-32d8f9b40ff8.png)
> 
> ![image](https://user-images.githubusercontent.com/1118931/170592632-56a70216-6b8b-48bd-98ed-57595928b6e1.png)
> 
> 

To fix that I believe you have to do 'holoiso-disable-sessions' in the recovery mode which is under advanced options when you first boot the menu

**Comment by SirTZN** [comment] 2022-05-26 23:41
> > > 
> > 
> > Started in recovery mode
> > 
> > 
> > 
> > cd /boot/grub
> > 
> > vim grub.cfg 
> > 
> > 
> > 
> > Editor:
> > 
> > ?splash
> > 
> > added "nvidia-drm.modeset=1"
> > 
> > ?!x
> > 
> > 
> > 
> > Rebooted still with same error
> > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/1118931/170592511-56bd659f-75b8-4062-9f5c-32d8f9b40ff8.png)
> > 
> > ![image](https://user-images.githubusercontent.com/1118931/170592632-56a70216-6b8b-48bd-98ed-57595928b6e1.png)
> > 
> > 
> 
> To fix that I believe you have to do 'holoiso-disable-sessions' in the recovery mode which is under advanced options when you first boot the menu

That's close but unfortunately it still doesn't let you load the steam UI, just the regular desktop (granted, that's just for me, but other people in this thread have also had that exact issue)

**Comment by Funky7Monkey** [comment] 2022-05-26 23:42
> NVIDIA users:
> 
> Edit /boot/grub/grub.cfg and add `nvidia-drm.modeset=1` after splash

`/etc/default/grub` should be edited, and `grub.cfg` rebuilt using `grub-mkconfig -o /boot/grub/grub.cfg`.

**Comment by mooock** [comment] 2022-05-26 23:47
> 
> To fix that I believe you have to do 'holoiso-disable-sessions' in the recovery mode which is under advanced options when you first boot the menu

it did take me further but now locked in this screen, i am only able to use the advanced boot options with booster, otherwise it will lock up sooner while loading to ramdisk.
![image](https://user-images.githubusercontent.com/1118931/170601168-700f7c62-db58-470a-9e9c-0da78e35aad8.png)

i did try to change back to enable, but then returned to the same issue again

**Comment by Timmyval123** [comment] 2022-05-26 23:48
> > To fix that I believe you have to do 'holoiso-disable-sessions' in the recovery mode which is under advanced options when you first boot the menu
> 
> it did take me further but now locked in this screen, i am only able to use the advanced boot options with booster, otherwise it will lock up sooner while loading to ramdisk. ![image](https://user-images.githubusercontent.com/1118931/170601168-700f7c62-db58-470a-9e9c-0da78e35aad8.png)
> 
> i did try to change back to enable, but then returned to the same issue again

Same here. Is there any way to open up a terminal in this screen ? I can't find away to do so

**Comment by SirTZN** [comment] 2022-05-26 23:56
> > NVIDIA users:
> > 
> > Edit /boot/grub/grub.cfg and add `nvidia-drm.modeset=1` after splash
> 
> `/etc/default/grub` should be edited, and `grub.cfg` rebuilt using `grub-mkconfig -o /boot/grub/grub.cfg`.

Ok so that got me really close. Now there is a startup screen, but it takes me back to login before bringing me to the steamos account selector.

**Comment by mooock** [comment] 2022-05-26 23:56
I also tried the proper Way to rebuild the grub. But still didn't fix.

**Comment by SirTZN** [comment] 2022-05-27 00:02
> > NVIDIA users:
> > 
> > Edit /boot/grub/grub.cfg and add `nvidia-drm.modeset=1` after splash
> 
> `/etc/default/grub` should be edited, and `grub.cfg` rebuilt using `grub-mkconfig -o /boot/grub/grub.cfg`.

Okay I actually got this working on "linux-neptune-dri (fallback initramfs)".

I'm not seasoned enough in arch to know but it now works!

**Comment by Funky7Monkey** [comment] 2022-05-27 00:09
> > To fix that I believe you have to do 'holoiso-disable-sessions' in the recovery mode which is under advanced options when you first boot the menu
> 
> it did take me further but now locked in this screen, i am only able to use the advanced boot options with booster, otherwise it will lock up sooner while loading to ramdisk. ![image](https://user-images.githubusercontent.com/1118931/170601168-700f7c62-db58-470a-9e9c-0da78e35aad8.png)
> 
> i did try to change back to enable, but then returned to the same issue again

I just tested an install without making a user correctly. That has reproduced this issue. Easiest solution is to reinstall. Make sure to add a root password for recovery mode, a username and password, as prompted. Along with that, run `holoiso-disable-sessions` in recovery mode (in advanced options in grub) again to get back to the point you were before.

Until https://github.com/theVakhovskeIsTaken/holoiso/commit/670b2c1266e9001bd86c59dfc87192c45c345155 is released, all Nvidia users will have to boot into recovery mode after you install and add `nvidia-drm.modeset=1` to grub as listed above.

**Comment by mooock** [comment] 2022-05-27 00:15
What username did you use. This time I payed more attention to what showed. And could quickly see something about invalid username.

**Comment by Timmyval123** [comment] 2022-05-27 00:24
> What username did you use. This time I payed more attention to what showed. And could quickly see something about invalid username.

I just changed my usernames and passwords on the next install and it took me to the steam OS setup. The resolution isn't right and most of the options are cut off

**Comment by Funky7Monkey** [comment] 2022-05-27 00:28
Usernames in Linux should only use alphanumeric characters and underscores to prevent problems with software that makes poor assumptions.

**Comment by Funky7Monkey** [comment] 2022-05-27 00:31
> > What username did you use. This time I payed more attention to what showed. And could quickly see something about invalid username.
> 
> I just changed my usernames and passwords on the next install and it took me to the steam OS setup. The resolution isn't right and most of the options are cut off

What resolution display are you using?

**Comment by Timmyval123** [comment] 2022-05-27 00:33
> > > What username did you use. This time I payed more attention to what showed. And could quickly see something about invalid username.
> > 
> > 
> > I just changed my usernames and passwords on the next install and it took me to the steam OS setup. The resolution isn't right and most of the options are cut off
> 
> What resolution display are you using?

1440p. A large chunk of the display on top is cut off, but it seems that some of the UI is just missing. it will make sounds when switching from selections that are invisible to me

**Comment by mooock** [comment] 2022-05-27 00:34
I did a new installation and selected 1 instead of booster. And used a name with 8+ lowercase. Also changed grub and disabled user. And now I could start default entry and see my username. Now I at a point with black screen after some loading that looks like a wrong refresh or something

**Comment by Timmyval123** [comment] 2022-05-27 00:37
> > > What username did you use. This time I payed more attention to what showed. And could quickly see something about invalid username.
> > 
> > 
> > I just changed my usernames and passwords on the next install and it took me to the steam OS setup. The resolution isn't right and most of the options are cut off
> 
> What resolution display are you using?

Is there a way to change the default resolution to 1440 through the recovery mode ?

**Comment by Funky7Monkey** [comment] 2022-05-27 00:44
> I did a new installation and selected 1 instead of booster. And used a name with 8+ lowercase. Also changed grub and disabled user. And now I could start default entry and see my username. Now I at a point with black screen after some loading that looks like a wrong refresh or something

Sounds like `gamescope-session` isn't launching correctly. Enter recovery mode, run `holoiso-disable-sessions` and reboot. once you see a log in prompt, switch to TTY4 (`Ctrl`+`Alt`+`F4`), log in, and run `gamescope-session`.

**Comment by mooock** [comment] 2022-05-27 00:46
For me the black screen was related to hdmi input now it works when removing hdmi and only have one dp input

**Comment by Funky7Monkey** [comment] 2022-05-27 00:56
> > > > What username did you use. This time I payed more attention to what showed. And could quickly see something about invalid username.
> > > 
> > > 
> > > I just changed my usernames and passwords on the next install and it took me to the steam OS setup. The resolution isn't right and most of the options are cut off
> > 
> > 
> > What resolution display are you using?
> 
> Is there a way to change the default resolution to 1440 through the recovery mode ?

See https://github.com/Samsagax/gamescope-session#configuration to change the resolution.

**Comment by CooperRecob** [comment] 2022-05-27 01:01
> > I did a new installation and selected 1 instead of booster. And used a name with 8+ lowercase. Also changed grub and disabled user. And now I could start default entry and see my username. Now I at a point with black screen after some loading that looks like a wrong refresh or something
> 
> Sounds like `gamescope-session` isn't launching correctly. Enter recovery mode, run `holoiso-disable-sessions` and reboot. once you see a log in prompt, switch to TTY4 (`Ctrl`+`Alt`+`F4`), log in, and run `gamescope-session`.

just tried that and I get an error saying that on line 175: kill

**Comment by Funky7Monkey** [comment] 2022-05-27 01:06
There should be more output there. Send everything it outputs.

Run `gamescope-session 2>&1 | tee output.txt` to have it output to the screen and to `output.txt`.

**Comment by mooock** [comment] 2022-05-27 01:08
![20220527_030140](https://user-images.githubusercontent.com/1118931/170608340-323e871e-4a33-4897-ab37-4ede37c14297.jpg)

I also struggle to get past the login when trying to load the profile

**Comment by KingOfCubes1** [comment] 2022-05-27 01:10
Outputs to the console `/usr/bin/gamescope-session: line 175: kill: (11242) - No such processnt32_t, win32_t, CVulkanTexture::createFlags, wlr_dmabuf_attributes*, uint32_t, uint32_t):`

**Comment by mooock** [comment] 2022-05-27 01:12
Just used the bootmenu fallback and now I was able to login

**Comment by CooperRecob** [comment] 2022-05-27 01:13
> There should be more output there. Send everything it outputs.
> 
> Run `gamescope-session 2>&1 | tee output.txt` to have it output to the screen and to `output.txt`.

The console prints `/usr/bin/gamescope-session: line 175: kill: (11242) - No such processnt32_t, uint32_t, uint32_t, CVulkanTexture::createFlags, wlr_dmabuf_attributes*, uint32_t, uint32_t):`

**Comment by CooperRecob** [comment] 2022-05-27 01:13
> Just used the bootmenu fallback and now I was able to login

how do you use that?

**Comment by mooock** [comment] 2022-05-27 01:21
> > Just used the bootmenu fallback and now I was able to login
> 
> how do you use that?

Just select advanced in when it boot. But your image requires the currect install where you are asked to select booster and so on. Here you need to have chosen the default selection otherwise this will not show up

**Comment by mooock** [comment] 2022-05-27 01:22
![20220527_032139](https://user-images.githubusercontent.com/1118931/170609722-de1ea018-4744-47e0-bf0d-0fbff4c0784d.jpg)

**Comment by CooperRecob** [comment] 2022-05-27 01:29
> > > Just used the bootmenu fallback and now I was able to login
> > 
> > 
> > how do you use that?
> 
> Just select advanced in when it boot. But your image requires the currect install where you are asked to select booster and so on. Here you need to have chosen the default selection otherwise this will not show up

were you able to login to an actual gamescope session or just the plasma 11 desktop enviroment?

**Comment by mooock** [comment] 2022-05-27 01:32
I am no sure what plasma means. But the gui is very laggy 
![20220527_033120](https://user-images.githubusercontent.com/1118931/170610657-f094743e-8e75-4da0-9e8b-6a74bb40e501.jpg)
![20220527_033035](https://user-images.githubusercontent.com/1118931/170610658-6affdfe9-611a-4811-a821-02eb518be33f.jpg)

**Comment by Timmyval123** [comment] 2022-05-27 01:34
> > I did a new installation and selected 1 instead of booster. And used a name with 8+ lowercase. Also changed grub and disabled user. And now I could start default entry and see my username. Now I at a point with black screen after some loading that looks like a wrong refresh or something
> 
> Sounds like `gamescope-session` isn't launching correctly. Enter recovery mode, run `holoiso-disable-sessions` and reboot. once you see a log in prompt, switch to TTY4 (`Ctrl`+`Alt`+`F4`), log in, and run `gamescope-session`.

I was able to login thanks to an old 720p monitor lying around. Now back on my regular monitor in plasma desktop mode it recognizes that my monitor is 1440p

**Comment by CooperRecob** [comment] 2022-05-27 01:37
> I am no sure what plasma means. But the gui is very laggy ![20220527_033120](https://user-images.githubusercontent.com/1118931/170610657-f094743e-8e75-4da0-9e8b-6a74bb40e501.jpg) ![20220527_033035](https://user-images.githubusercontent.com/1118931/170610658-6affdfe9-611a-4811-a821-02eb518be33f.jpg)

plasma is the desktop mode of steamos and I am confused on how to get to where you are, I am suck only being able to log into the desktop mode and run the gamescope mode inside a window there

**Comment by mooock** [comment] 2022-05-27 01:43
i am not sure if the fallback mode, was the key, but when i was reaching the login screen, it was shortly loaded, and returned me to the login screen again retrying a lot of time sudden showed steam was downloading some updates, and after that it was able to bring me further. but something is still wrong, the game cannot start, and it looks like the nvidia driver is not loaded or having acceleration activated

**Comment by PeavUK** [comment] 2022-05-27 01:43
I'm also getting a similar issue as Timmyval123 but in my case it looks like a vulkan issue. I can get into the x11 desktop after disabling the sessions. Checked info centre > graphics > vulkan and no mention of AMD but loader error mentioning ICD libGLX_nvidia_so.0. This is a fresh install with the snapshot 5 iso. I did do an install with a previous build a few weeks back that worked other than a scaling issue, so went back to manjaro while I waited for newer builds to come out. 

I noticed during the install a conflict error between mesa and mesa-steamos.

In an attempt to fix the vulkan issue - i installed the packages that are referenced in the holoinstall script - but the deck ui fails to run.

If screen shots are required, I can do a reinstall, but it'll have to wait until later in the morning (2:30 am here).
GPU Option 1 picked during install.
CPU=10700k and GPU is RX6800

**Comment by Timmyval123** [comment] 2022-05-27 01:46
> > I am no sure what plasma means. But the gui is very laggy ![20220527_033120](https://user-images.githubusercontent.com/1118931/170610657-f094743e-8e75-4da0-9e8b-6a74bb40e501.jpg) ![20220527_033035](https://user-images.githubusercontent.com/1118931/170610658-6affdfe9-611a-4811-a821-02eb518be33f.jpg)
> 
> plasma is the desktop mode of steamos and I am confused on how to get to where you are, I am suck only being able to log into the desktop mode and run the gamescope mode inside a window there

remember the blue screen that asks you to select user and enter password that was locked. If you get back there you should be able to select plasma instead of steam OS in the top left. Then enter your password and you will have desktop UI

**Comment by Funky7Monkey** [comment] 2022-05-27 01:52
> I'm also getting a similar issue as Timmyval123 but in my case it looks like a vulkan issue. I can get into the x11 desktop after disabling the sessions. Checked info centre > graphics > vulkan and no mention of AMD but loader error mentioning ICD libGLX_nvidia_so.0. This is a fresh install with the snapshot 5 iso. I did do an install with a previous build a few weeks back that worked other than a scaling issue, so went back to manjaro while I waited for newer builds to come out.
> 
> I noticed during the install a conflict error between mesa and mesa-steamos.
> 
> In an attempt to fix the vulkan issue - i installed the packages that are referenced in the holoinstall script - but the deck ui fails to run.
> 
> If screen shots are required, I can do a reinstall, but it'll have to wait until later in the morning (2:30 am here). GPU Option 1 picked during install. CPU=10700k and GPU is RX6800

Please open an new issue to prevent more clutter. If you can give the output for the following as well, it'll make debugging faster

> Sounds like `gamescope-session` isn't launching correctly. Enter recovery mode, run `holoiso-disable-sessions` and reboot. once you see a log in prompt, switch to TTY4 (`Ctrl`+`Alt`+`F4`), log in, and run `gamescope-session`.

**Comment by mooock** [comment] 2022-05-27 01:57
Just tried switching to plasma and for that et freeze up in the loading screen

**Comment by CooperRecob** [comment] 2022-05-27 02:00
just opened a new ticket at https://github.com/theVakhovskeIsTaken/holoiso/issues/209

**Comment by Olly06** [comment] 2022-05-27 17:51
I have the same issue and if I try to go in the rescue mode it gives that the root account is locked, how can I resolve? 
![Uploading 1653673867218.jpg…]()

**Comment by mooock** [comment] 2022-05-27 18:01
> 

you might have selected the wrong selection from the installation, or not added the nvidia parameter to the grub loader as written earlier in the thread. but for now it don't seems to work with nvidia. before something is fixed

**Comment by Olly06** [comment] 2022-05-27 19:48
> 

I selected the full installation and the selected the amd gpu because of my 5600g, is that compatible or not?

**Comment by ASOwnerYT** [comment] 2022-05-27 23:20
I think I found the issue. I'm using a gaming laptop with an Nvidia dGPU. I had the exact same issue, and I connected an external monitor and it just worked on the external monitor. It looks like Gamescope is just having issues using the laptop screen.

Edit: I would also like to mention that the Steamdeck UI is really laggy this way and also it doesn't work with my laptop screen

**Comment by PeavUK** [comment] 2022-05-27 23:52
> > I'm also getting a similar issue as Timmyval123 but in my case it looks like a vulkan issue. I can get into the x11 desktop after disabling the sessions. Checked info centre > graphics > vulkan and no mention of AMD but loader error mentioning ICD libGLX_nvidia_so.0. This is a fresh install with the snapshot 5 iso. I did do an install with a previous build a few weeks back that worked other than a scaling issue, so went back to manjaro while I waited for newer builds to come out.
> > I noticed during the install a conflict error between mesa and mesa-steamos.
> > In an attempt to fix the vulkan issue - i installed the packages that are referenced in the holoinstall script - but the deck ui fails to run.
> > If screen shots are required, I can do a reinstall, but it'll have to wait until later in the morning (2:30 am here). GPU Option 1 picked during install. CPU=10700k and GPU is RX6800
> 
> Please open an new issue to prevent more clutter. If you can give the output for the following as well, it'll make debugging faster
> 
> > Sounds like `gamescope-session` isn't launching correctly. Enter recovery mode, run `holoiso-disable-sessions` and reboot. once you see a log in prompt, switch to TTY4 (`Ctrl`+`Alt`+`F4`), log in, and run `gamescope-session`.

My issue was fixed in the latest iso release that reverts the vulkan setup back to vulkan-radeon.

**Comment by jnackmclain** [comment] 2022-05-28 02:09
I have the same issues on my laptop and nothing here in the threads seems to help.
Asus G401I
Ryzen 7 4000 series cpu
GTX 1650 gpu

**Comment by jnackmclain** [comment] 2022-05-28 16:56
I kind of made some progress? I built the iso from the latest commit. Followed directions here, disabled sessions, boot into TTY, try to launch gamescope directly. This was the output ![image](https://user-images.githubusercontent.com/55568980/170835116-e4f5e703-2b8f-4e6b-ba31-67ea5e2ae8ba.jpeg)
Says no DisplayPort. My laptop does DisplayPort over usb c. I just got a usb c dongle that does hdmi, and plugged that in.

The desktop session confirmed I am in DisplayPort mode for that connection. I reenabled sessions and rebooted. And I do get a screen! However, the progress bar goes about 1fps, and it loops this. I cannot continue.
![image](https://user-images.githubusercontent.com/55568980/170835175-c7c7797c-0e1c-43f9-8bec-7c6b9a0b3c65.jpeg)

**Comment by jnackmclain** [comment] 2022-05-28 17:12
From above, I rebooted and logged back into Plasma. I ensured I was connected to wifi, and disabled my laptop display. This way I am only running output to my external display to register displayport. In plasma I ran `gamescope-session`
A steam window did pop up and make the intro sound and play the loading animation (at good fps) but it crashed within a few seconds without showing other windows. Here is the whole output of running `gamescope-session` 
[output.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/8791520/output.txt)

**Comment by jnackmclain** [comment] 2022-05-28 17:15
Without rebooting, I ran gamescope-session one more time. This time I got all the way to choosing my wifi network within gamescope, then my laptop rebooted

**Comment by jnackmclain** [comment] 2022-05-28 17:20
Rebooting again, I switched to TTY from the login screen and ran gamescope-session again. This time the session started up fine (external display), I logged in, and can see my library. Performance in gamescope is pretty glitchy and low fps. I hit power then "switch to desktop" and the session is frozen at "switching to desktop"

**Comment by jnackmclain** [comment] 2022-05-28 17:53
Enabling sessions again let's me boot into deck ui with my external display just fine. However, performance seems really bad in games, almost like running off integrated graphics with my ryzen 7 4000 series. I have a 1660ti and I can barely get 30fps in crash bandicoot trilogy, 1280x800. And I don't get a full 60fps in Celeste, window size 3x.
My cpu is under heavy load in these smaller titles

**Comment by theVakhovskeIsTaken** [comment] 2022-05-29 21:41
>_*No matter how great job NVIDIA and plagman has done on adapting each other, this combination MAY still be buggy, please do not report any problems to me aside from OOBE, session launching and switching and overlay management, if you encounter any problems in-gamescope, please open issue in https://github.com/Plagman/gamescope/issues_

**Closed as completed by theVakhovskeIsTaken** 2022-05-29 21:41 UTC
