### ISSUE TITLE
All audio goes through "Echo Cancel Sink"

### ISSUE THREAD

**Issue by aaronson2012** [holoiso-eol/holoiso#300] opened 2022-06-21 13:22 UTC
I was having an issue with no audio playback on my machine when I realized that all my audio is going through a "Echo Cancel Sink" device, completely ignoring my default device (HDMI audio).

For now I'm fixing it with "pactl unload-module module-echo-cancel" after every reboot.

Thanks!

**Comment by Trozmagon** [comment] 2022-06-22 21:36
I also have the same issue and same command is resolving it until reboot. Let me know if there are any logs I can provide to help resolve this.

**Comment by tonikarppi** [comment] 2022-06-26 10:02
I'm also experiencing this issue running on a desktop connected to a TV over HDMI. I wrote a script that automatically unloads the module on boot so you don't have to do it manually. I'll share it in case anyone wants to use it.

Create the file ~/.scripts/unload-echo-cancel.sh with the following content:
```bash
#!/bin/bash

while :; do
  output=$(pactl unload-module module-echo-cancel 2>&1)
  if [[ -z "$output" ]]; then
    break
  fi
  echo 'waiting...'
  sleep 1
done
```

Make the file executable: `chmod +x ~/.scripts/unload-echo-cancel.sh`

Create the file ~/.config/systemd/user/unload-echo-cancel.service with the following content:
```bash
[Unit]
Description=Unload Echo-Cancel Module

[Service]
Type=oneshot
ExecStart=%h/.scripts/unload-echo-cancel.sh

[Install]
WantedBy=default.target
```

Enable the service so it starts on boot: `systemctl --user enable unload-echo-cancel.service`

**Comment by tonikarppi** [comment] 2022-07-01 15:11
Audio is working for me now without workarounds after the latest update

**Comment by frzifus** [comment] 2022-07-12 21:43
Is it still an issue for you @aaronson2012 @Trozmagon ? I have a similar problem at the moment. unfortunately it cannot be fixed by unloading the echo cancel module.  https://github.com/theVakhovskeIsTaken/holoiso/issues/355

**Comment by Trozmagon** [comment] 2022-07-12 21:48
> Is it still an issue for you @aaronson2012 @Trozmagon ? I have a similar problem at the moment. unfortunately it cannot be fixed by unloading the echo cancel module. #355

I was able to resolve it with tonikarppi's script however I haven't checked it since that day, also I haven't had the time to try the new system updates so I'm unable to comment on that sorry.

**Comment by tonikarppi** [comment] 2022-07-12 22:04
I'd recommend joining the Telegram channel and trying the system update commands listed there to see if that fixes your issues.

**Comment by johnynfulleffect** [comment] 2022-08-11 12:55
> I'm also experiencing this issue running on a desktop connected to a TV over HDMI. I wrote a script that automatically unloads the module on boot so you don't have to do it manually. I'll share it in case anyone wants to use it.
> 
> Create the file ~/.scripts/unload-echo-cancel.sh with the following content:
> 
> ```shell
> #!/bin/bash
> 
> while :; do
>   output=$(pactl unload-module module-echo-cancel 2>&1)
>   if [[ -z "$output" ]]; then
>     break
>   fi
>   echo 'waiting...'
>   sleep 1
> done
> ```
> 
> Make the file executable: `chmod +x ~/.scripts/unload-echo-cancel.sh`
> 
> Create the file ~/.config/systemd/user/unload-echo-cancel.service with the following content:
> 
> ```shell
> [Unit]
> Description=Unload Echo-Cancel Module
> 
> [Service]
> Type=oneshot
> ExecStart=%h/.scripts/unload-echo-cancel.sh
> 
> [Install]
> WantedBy=default.target
> ```
> 
> Enable the service so it starts on boot: `systemctl --user enable unload-echo-cancel.service`

Thanks for the excellent write up!  I implemented this, and I do not see the Echo Cancel Audio interface anymore.  However, I still don't get audio on the deck.  Just when using bluetooth.

Hardware: 512GB SteamDeck
OS Version: holo 3.3 (snapshot20220716.2021)
Kernel: 5.13.0-valve22-1-neptune-02213

> Audio is working for me now without workarounds after the latest update

No updates out there checking from the command line.

Anyone have any ideas?

**Comment by rezo552** [comment] 2022-08-31 08:10
I have the same issue, after unloading the module, I can select the audio device but still no audio. Any hint is appreciated

**Comment by frzifus** [comment] 2022-08-31 09:01
@rezo552 is it no audio in general or just in games on the steamdeckui?

**Comment by rezo552** [comment] 2022-08-31 09:06
In general no audio. If I unload the echo sink module, I can select the audio device HDMI but still no audio. If I switch over to desktop mode then I can see it inactive. Then if I change the configuration with pavucontrol then HDMI is working in desktop mode but when I switch over to Steam Deck then the intro sound comes but no sound in UI and no sound in games. This is where I am right now...

**Comment by rezo552** [comment] 2022-08-31 09:25
Just for recording here was the solution:

pactl unload-module module-echo-cancel
pactl set-card-profile  alsa_card.pci-0000_07_00.0 output:hdmi-stereo

**Comment by S1ngl3-x** [comment] 2022-09-23 07:31
> > I'm also experiencing this issue running on a desktop connected to a TV over HDMI. I wrote a script that automatically unloads the module on boot so you don't have to do it manually. I'll share it in case anyone wants to use it.
> > Create the file ~/.scripts/unload-echo-cancel.sh with the following content:
> > ```shell
> > #!/bin/bash
> > 
> > while :; do
> >   output=$(pactl unload-module module-echo-cancel 2>&1)
> >   if [[ -z "$output" ]]; then
> >     break
> >   fi
> >   echo 'waiting...'
> >   sleep 1
> > done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make the file executable: `chmod +x ~/.scripts/unload-echo-cancel.sh`
> > Create the file ~/.config/systemd/user/unload-echo-cancel.service with the following content:
> > ```shell
> > [Unit]
> > Description=Unload Echo-Cancel Module
> > 
> > [Service]
> > Type=oneshot
> > ExecStart=%h/.scripts/unload-echo-cancel.sh
> > 
> > [Install]
> > WantedBy=default.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Enable the service so it starts on boot: `systemctl --user enable unload-echo-cancel.service`
> 
> Thanks for the excellent write up! I implemented this, and I do not see the Echo Cancel Audio interface anymore. However, I still don't get audio on the deck. Just when using bluetooth.
> 
> Hardware: 512GB SteamDeck OS Version: holo 3.3 (snapshot20220716.2021) Kernel: 5.13.0-valve22-1-neptune-02213
> 
> > Audio is working for me now without workarounds after the latest update
> 
> No updates out there checking from the command line.
> 
> Anyone have any ideas?

I can confirm this has fixed my issue. Thank you.
Could this be fixed by the maintainer so we do not have to create our own bash-script services? Or is this an issue on Valve's side?

Also will this running service collide with something later on?

**Closed as completed** 2023-09-08 08:09 UTC
