### ISSUE TITLE
Can't install alongside existing OS/Partition

### ISSUE THREAD

**Issue by e-legy** [holoiso-eol/holoiso#362] opened 2022-07-14 04:25 UTC
I have 100GB unallocated free space, it failed to create partition. I also tried 57GB unallocated free space, because the author suggest to allocate 57GB or 500GB free space for stable experience, as allocating different sizes causes mispartition issues. But the result is the same.
```shell
Calculating start and end of free space...
expr: non-integer argument
expr: non-integer argument
partitioning:[:111: unknown condition: -gt

Creating partitions..
Error: Invalid number.
Error: Partition doesn't exist.
Error: Partition doesn't exist.
Error: Invalid number.
Error: Invalid number.
mkfs.fat 4.2 (2021-01-31)
mkfs.ufat: unable to open /dev/nvme0n1p4: No such file or directory
open: No such file or directory
btrfs-progs v5.16
See http://btrfs.wiki.kernel.org for nore information.

ERROR: mount check: cannot open /deu/nvme0n1p5: No such file or directory
ERROR: cannot check mount status of /deu/nvme0n1p5: No such file or directory
ERROR: unable to access /dev/nume0n1p5: No such file or directory
mke2fs 1.46.5 (30-Dec-2021)
The file /dev/nume0n1p6 does not exist and no size was specified.
e2label: No such file or directory while trying to open /dev/nvme0n1p6
Couldn't find valid filesystem superblock.

Partitioning complete, mounting and pastrapping...
Intel CPU detected, Installing Intel ucode...
mount: /var/mnt: special device /dev/nvme0n1p5 does not exist.

Error: Something went wrong when mounting root partitions, Please try again!
```

**Comment by wynn1212** [comment] 2022-07-14 05:04
Duplicate of #354 

This issue has now being address.
https://github.com/theVakhovskeIsTaken/holoiso-install-script/pull/4

**Closed as completed** 2023-09-08 08:09 UTC
