### ISSUE TITLE
Wifi not working Aya Neo Pro 2021, Mediatek MT7921K RZ608

### ISSUE THREAD

**Issue by TypeZaxter** [holoiso-eol/holoiso#65] opened 2022-05-08 22:39 UTC
Just ethernet works.

**Comment by ruineka** [comment] 2022-05-08 22:42
I confirmed this on my Aya Neo Pro as well. I'm working on a solution for the OneXplayer and Aya Neo issues now.

**Comment by TypeZaxter** [comment] 2022-05-08 22:44
Thank you so much, just post here if you figure it out

**Comment by Super-6-1** [comment] 2022-05-10 01:39
This is taken from reddit over in the ayaneo subreddit. 

`Fixing Wifi on the Aya Neo

The Aya Neo uses the Mediatek MT7921 wifi card, which was only supported in Linux recently. Hence, the drivers are missing from the Linux kernel used in Valve's current SteamOS image. HoloISO also comes with an updated Linux kernel from Steam's Arch repository, 5.16.2, but unfortunately there is a bug in this version of the kernel that prevents wifi from working. To fix this, we'll need to install the latest kernel, 5.16.5.

These steps only need to be followed if Steam's Arch packages repository only has Linux kernel version 5.16.2, so if the repo gets updated someone let me know in the comments.

After running the holoinstall script, run arch-chroot /mnt to access the installed SteamOS (alternatively, you can run these commands after booting into SteamOS and switching to desktop mode, just add sudo to the front of these commands).

Run pacman -Sy nano to install the nano text editor.

Run nano /etc/pacman.d/mirrorlist, then in the text editor you want to comment out (add "#" in front of) the Server = https://steamdeck-packages... line. Then add a new line with Server = <url>, where <url> is one of the URLs listed in the [Arch Mirrorlist](https://archlinux.org/mirrorlist/). Press Ctrl+X and save changes.

Run nano /etc/pacman.conf, then in the text editor you want to scroll down to the repositories section and comment out (add '#' in front of) [jupiter], [holo] and the two lines below each of those. Press Ctrl+X and save changes.

Run pacman -Syu. This will update all packages, including updating the linux kernel to 5.16.5, which has fixes for the wifi. It may fail the first time, just run it again.

After the update is complete (you may need to confirm a few things), edit the mirrorlist file and pacman.conf file from steps 3 and 4 to undo the changes you added.

Next, we'll change the startup menu so it always boots up with the 5.16.5 kernel.

Run nano /etc/default/grub. Find #GRUB_DISABLE_SUBMENU=... and uncomment it (delete the "#" in front of it). Find GRUB_DEFAULT=0 and change the 0 to 2.

You can also change the GRUB_TIMEOUT=5 to decrease/increase the amount of time before the default option is chosen.

Press Ctrl+X and save the changes. Then run grub-mkconfig -o /boot/grub/grub.cfg.

At this point, you can restart (reboot or poweroff) and boot into your HoloISO install. Go through the Steam Deck OOBE setup process and check that the install is fine and working, and that the wifi connects without issues.` 


Edit notes: When you do this, make sure to change GRUB_DEFAULT=0 to 3. This is how it works on mine, your maybe different. 
Link to it is here. https://www.reddit.com/r/ayaneo/comments/uku3uh/guide_to_installing_holoiso_unofficial_steamos_30/

**Comment by Furaihai** [comment] 2022-05-10 10:08
What about this fix script? Does this patch the gaps with steamOS and the Aya Neo?

https://github.com/ShadowBlip/aya-neo-fixes

**Comment by theVakhovskeIsTaken** [comment] 2022-05-10 16:25
I will try to backport these drivers to Steam Deck kernel later, since it's opensource.

But i will suggest you to use above install method for now.

**Comment by Furaihai** [comment] 2022-05-10 17:24
I don't have an ethernet to USB-C adapter for my Aya Neo so the above fix is useless for me. Looking forward to when the drivers get implemented or if anyone posts a way to implement the fix script to the holoiso image

**Comment by famiglia-84** [comment] 2022-05-10 21:48
@Furaihai 
I was able to connect to wifi and run the holoinstall script with the instructions from this video: https://www.youtube.com/watch?v=Xr2BO4IPqro&t=549s   (8min:16sec mark)
after the holoinstall script is done, you can then follow the instructions from @Super-6-1 's comment

**Comment by fosterjeffrey93** [comment] 2022-05-11 15:14
> I don't have an ethernet to USB-C adapter for my Aya Neo so the above fix is useless for me. Looking forward to when the drivers get implemented or if anyone posts a way to implement the fix script to the holoiso image

You can tether your phone through the USB ports. Its what I do when ever I have to bypass the WiFi for whatever reason

**Comment by pastaq** [comment] 2022-05-12 03:39
Hi. I maintain the aya-neo-fixes package, so I have some insight into this issue. I recently removed this WiFi fix from the package as the most recent kernel has (somewhat) better support for this kernel. Here are the main issues that the MT7921K (2021 Pro and above) have in Linux at the moment:
- Kernels < 5.16.5 don't have the PCI device ID in the driver. Simple UDEV/modprobe rules can resolve this until you are able to update the kernel.
- The system will kernel panic after reboot or suspend. This is due to bad power management in the driver. This affects all aya-neo's. Fixes for this are in ```aya-neo-fixes-git``` 

For the below files, place 99-rz608.rules in ```/etc/udev/rules.d``` and rz608.conf in ```/etc/modprobe.d/```, then reboot and wifi should work. 644 permissions for all files.


## 99-rz608.rules
```
SUBSYSTEM=="drivers", DEVPATH=="/bus/pci/drivers/mt7921e", ATTR{new_id}="14c3 0608"
```

## rz608.conf
```
alias pci:v000014C3d00000608sv*sd*bc*sc*i* mt7921e
```
You can add these to your archiso as well so the installer works better. This will probably solve #102

**Comment by theVakhovskeIsTaken** [comment] 2022-05-12 06:36
> Hi. I maintain the aya-neo-fixes package, so I have some insight into this issue. I recently removed this WiFi fix from the package as the most recent kernel has (somewhat) better support for this kernel. Here are the main issues that the MT7921K (2021 Pro and above) have in Linux at the moment:
> - Kernels < 5.16.5 don't have the PCI device ID in the driver. Simple UDEV/modprobe rules can resolve this until you are able to update the kernel.
> - The system will kernel panic after reboot or suspend. This is due to bad power management in the driver. This affects all aya-neo's. Fixes for this are in ```aya-neo-fixes-git``` 
> 
> For the below files, place 99-rz608.rules in ```/etc/udev/rules.d``` and rz608.conf in ```/etc/modprobe.d/```, then reboot and wifi should work. 644 permissions for all files.
> 
> 
> ## 99-rz608.rules
> ```
> SUBSYSTEM=="drivers", DEVPATH=="/bus/pci/drivers/mt7921e", ATTR{new_id}="14c3 0608"
> ```
> 
> ## rz608.conf
> ```
> alias pci:v000014C3d00000608sv*sd*bc*sc*i* mt7921e
> ```
> You can add these to your archiso as well so the installer works better. This will probably solve #102 

Amazing!! open same issue at https://github.com/thevakhovskeistaken/holoiso_install_main so i won't forget it later

**Comment by theVakhovskeIsTaken** [comment] 2022-05-14 16:35
Fixed in kernel as of https://github.com/theVakhovskeIsTaken/valve_linux_neptune/commit/a996fe00180a1ca975a23f92be7a5d503d7b2a3b

**Closed as completed by theVakhovskeIsTaken** 2022-05-14 16:35 UTC
