### ISSUE TITLE
Packages won't sync

### ISSUE THREAD

**Issue by eggprez** [holoiso-eol/holoiso#12] opened 2022-05-03 20:48 UTC
Sorry I'm a Linux super newbie but when trying to install with holoinstall cmd all of the packages fail to sync and therefore the installation does not work. I'm connected through ethernet and getting a good ping so I don't know why this would be an issue but good luck and thanks for doing this!

**Comment by eggprez** [comment] 2022-05-03 20:58
This issue was on my ayaneo (2021 with 4700u) but my oneXplayer  (5700u) had no issue

**Comment by forrestlay** [comment] 2022-05-04 10:24
I also have issues with packages failing to sync on my Aya Neo 2021. Specifically, the "pacman -Sy" part of the holoinstall script will fail due to issues connecting to "steamdeck-packages.steamos.cloud", even though when I ping that domain it works fine.

From some Googling, this might be caused due to an [issue with the MT7921e Wifi card used in the Aya Neo that arises under the currently used Arch kernel, version 5.16.2](https://bbs.archlinux.org/viewtopic.php?id=273641). The issue is apparently fixed with kernel version 5.16.5. So if possible, I and any other Aya Neo users would appreciate if the Arch kernel on the install media could have the kernel updated to that version.

**Comment by theVakhovskeIsTaken** [comment] 2022-05-04 10:28
> I also have issues with packages failing to sync on my Aya Neo 2021. Specifically, the "pacman -Sy" part of the holoinstall script will fail due to issues connecting to "steamdeck-packages.steamos.cloud", even though when I ping that domain it works fine.
> 
> From some Googling, this might be caused due to an [issue with the MT7921e Wifi card used in the Aya Neo that arises under the currently used Arch kernel, version 5.16.2](https://bbs.archlinux.org/viewtopic.php?id=273641). The issue is apparently fixed with kernel version 5.16.5. So if possible, I and any other Aya Neo users would appreciate if the Arch kernel on the install media could have the kernel updated to that version.
> 
> 

Just to confirm few things. Does running ping google.com work fine in ISO? If yes, then i might *try* to ship Arch's latest kernel from their mirrors, rather than Deck's own ones

**Comment by forrestlay** [comment] 2022-05-04 11:11
Yes, pinging google.com works. However, I've just realised that once Steam OS is installed, the wifi card won't work anyway because its on an even older kernel. For now Aya Neo users will need a USB ethernet adapter to install, so I think the current kernel will be fine for now.

**Comment by theVakhovskeIsTaken** [comment] 2022-05-04 13:27
> Yes, pinging google.com works. However, I've just realised that once Steam OS is installed, the wifi card won't work anyway because its on an even older kernel. For now Aya Neo users will need a USB ethernet adapter to install, so I think the current kernel will be fine for now.

So, looks like, i'll have to ship `core/linux` on final installation too. Because there is no backported DKMS for your WiFi IC.

**Comment by theVakhovskeIsTaken** [comment] 2022-05-05 08:17
> Yes, pinging google.com works. However, I've just realised that once Steam OS is installed, the wifi card won't work anyway because its on an even older kernel. For now Aya Neo users will need a USB ethernet adapter to install, so I think the current kernel will be fine for now.

![image](https://user-images.githubusercontent.com/97450182/166885968-1584a347-054e-4e55-b568-c9159af381ac.png)

Next release will ship both SD and Arch kernels.

**Closed as completed by theVakhovskeIsTaken** 2022-05-05 08:17 UTC
