### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by USL5264** [holoiso-eol/holoiso#358] opened 2022-07-13 08:41 UTC
## Your Issue:
```
Unable to install for Dual Boot
```

## Your device's full specs
```
CPU: Intel i5 8250u 
GPU: Intel UHD620
```

## Your OS version
snapshot19700101_1011-beta2a
```

## Your installation type:
```
deckperience
```

Unable to install. Getting Partition does not exist even though I am using a unallocated space of 500gb

**Comment by USL5264** [comment] 2022-07-13 08:42
![Uploading 4BE0F10C-5BE0-4356-BEE2-6DA5D397A337.jpeg…]()

**Comment by wynn1212** [comment] 2022-07-14 02:52
This issue has now being address.
https://github.com/theVakhovskeIsTaken/holoiso-install-script/pull/4

**Comment by wynn1212** [comment] 2022-07-14 03:02
Duplicate of #354

**Closed as completed** 2023-09-08 08:09 UTC
