### ISSUE TITLE
Issues with New Onexplayer Mini Pro (Ryzen 7 6800U)

### ISSUE THREAD

**Issue by Nagakuro** [holoiso-eol/holoiso#619] opened 2022-11-26 04:10 UTC
So I've been trying to install HoloISO with the offline 3.1 installer and after I get Steam OS installed the Game mode UI is upside down, and then on top of that connecting it to an external monitor and trying to finish the OOBE Steam force shuts down after selecting internet and trying to update, and it constantly boot loops, gets right back to it and steam force shuts down. 

I didn't have these issues with my Ayaneo Air Pro, so this is really infuriating I just got this Onexplayer Mini 6800U which I wanna put head to head with the Steam Deck I have for testing with SteamOS but can't cause of this issue.

**Comment by Macdanight** [comment] 2022-11-27 08:49
+1 I am also having the same issue. Display is upside down on the OneXplayer mini pro.

**Comment by Slimer012** [comment] 2022-12-02 12:52
Same here.  I finally got an install to complete. I used the 20221106_1516 offline installer.  Is that the same as the 3.1? Loving the look and feel!  Alas, the Gaming Mode is completely upside down.  It is, obviously, right side up when I connect an external monitor.  I'm sure this is because the native orientation of the display panel in the oxp mini pro 6800U is 180° different than any other handheld I've used.  I sure do wish there was a setting we could change.  I'm guessing it's hardcoded, though :(

**Comment by ruineka** [comment] 2022-12-10 10:36
The DMI changed for the OXP Pro. All my work was upstreamed to gamescope, so rotation should never be an issue anymore. To rotate the display the new DMI string needs to be added to the device quirks or a kernel panel needs to be submitted. I'll start working on this to get this rolling.

To elaborate you can use `--force-orientation left` in the `gamescope-session` script located at `/usr/bin/gamescope-session` until the DMI gets added to automatically handle this in Holoiso.

**Comment by doberman579** [comment] 2022-12-10 11:47
Thank you, the gamescope trick works.
But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
Are there any tricks to configure buttons and activate Bluetooth properly?

**Comment by ruineka** [comment] 2022-12-10 12:23
> Thank you, the gamescope trick works.
> But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> Are there any tricks to configure buttons and activate Bluetooth properly?

I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.

go to desktop mode. Open the konsole and copy paste this

```
git clone
https://github.com/ShadowBlip/HandyGCCS.git
cd HandyGCCS
sudo make install

**Comment by doberman579** [comment] 2022-12-10 12:51
Thank you. I note that the Home button activate the right menu, so something work, but not sure that everything is ok. Because keyboard and turbo button don't give anything. Do I need to activate something else after this procedure?

**Comment by ruineka** [comment] 2022-12-10 15:27
> Thank you. I note that the Home button activate the right menu, so something work, but not sure that everything is ok. Because keyboard and turbo button don't give anything. Do I need to activate something else after this procedure?

Turbo itself isn't able to be reassigned on it's own. Keyboard comes up in games and text fields only now. This is true even on the Steam Deck itself.

Turbo changes the TDP at a firmware level on OXP devices.

**Comment by Tolan87** [comment] 2022-12-11 15:06
I think new updates has fixed the orientation problem, on my OXP Mini Pro it´s working without change the gamescope-session.

Turbo Button is working, it´s changed to 28w from 15w and back.

It can be possible you need to switch to Desktop Mode and update the binaries over Discovery.

**Comment by ruineka** [comment] 2022-12-11 15:10
> I think new updates has fixed the orientation problem, on my OXP Mini Pro it´s working without change the gamescope-session.
> 
> Turbo Button is working, it´s changed to 28w from 15w and back.
> 
> It can be possible you need to switch to Desktop Mode and update the binaries over Discovery.

Turbo should always work because its not OS controlled, it's being handled by the EC firmware.

Glad to hear that the updated DMI strings made its way to the device quirks if it's now working.

**Comment by doberman579** [comment] 2022-12-13 19:54
> > Thank you, the gamescope trick works.
> > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > Are there any tricks to configure buttons and activate Bluetooth properly?
> 
> I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> 
> go to desktop mode. Open the konsole and copy paste this
> 
> ```
> git clone
> https://github.com/ShadowBlip/HandyGCCS.git
> cd HandyGCCS
> sudo make install
> ```

Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?

**Comment by ruineka** [comment] 2022-12-13 20:08
> > > Thank you, the gamescope trick works.
> > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > 
> > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > 
> > go to desktop mode. Open the konsole and copy paste this
> > 
> > ```
> > git clone
> > https://github.com/ShadowBlip/HandyGCCS.git
> > cd HandyGCCS
> > sudo make install
> > ```
> 
> Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?

Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.

Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?

**Comment by doberman579** [comment] 2022-12-13 20:30
> > > > Thank you, the gamescope trick works.
> > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > 
> > > 
> > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > go to desktop mode. Open the konsole and copy paste this
> > > ```
> > > git clone
> > > https://github.com/ShadowBlip/HandyGCCS.git
> > > cd HandyGCCS
> > > sudo make install
> > > ```
> > 
> > 
> > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> 
> Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> 
> Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?

So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad

**Comment by ruineka** [comment] 2022-12-13 20:34
> > > > > Thank you, the gamescope trick works.
> > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > 
> > > > 
> > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > go to desktop mode. Open the konsole and copy paste this
> > > > ```
> > > > git clone
> > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > cd HandyGCCS
> > > > sudo make install
> > > > ```
> > > 
> > > 
> > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > 
> > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > 
> > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> 
> So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad

It means that the service is failing to start up on boot automatically.

I'm curious what does `sudo systemctl enable handycon.service` do for you?

**Comment by doberman579** [comment] 2022-12-13 20:45
> > > > > > Thank you, the gamescope trick works.
> > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > 
> > > > > 
> > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > ```
> > > > > git clone
> > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > cd HandyGCCS
> > > > > sudo make install
> > > > > ```
> > > > 
> > > > 
> > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > 
> > > 
> > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > 
> > 
> > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> 
> It means that the service is failing to start up on boot automatically.
> 
> I'm curious what does `sudo systemctl enable handycon.service` do for you?

The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)

**Comment by ruineka** [comment] 2022-12-13 21:29
> > > > > > > Thank you, the gamescope trick works.
> > > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > > 
> > > > > > 
> > > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > > ```
> > > > > > git clone
> > > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > > cd HandyGCCS
> > > > > > sudo make install
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > > 
> > > > 
> > > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > > 
> > > 
> > > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> > 
> > It means that the service is failing to start up on boot automatically.
> > 
> > I'm curious what does `sudo systemctl enable handycon.service` do for you?
> 
> The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)

We'll need to do some digging to see why exactly the service is seemingly being disabled on Holoiso. The Bluetooth situation shouldn't be related, I'm guessing the issue was found and resolved in the update.

P.S. No problem, we all start somewhere and it's the willingness to figure things out that gives us the experience we lack coming into something.

**Comment by doberman579** [comment] 2022-12-13 22:10
> > > > > > > > Thank you, the gamescope trick works.
> > > > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > > > 
> > > > > > > 
> > > > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > > > ```
> > > > > > > git clone
> > > > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > > > cd HandyGCCS
> > > > > > > sudo make install
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > > > 
> > > > > 
> > > > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > > > 
> > > > 
> > > > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> > > 
> > > 
> > > It means that the service is failing to start up on boot automatically.
> > > I'm curious what does `sudo systemctl enable handycon.service` do for you?
> > 
> > 
> > The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)
> 
> We'll need to do some digging to see why exactly the service is seemingly being disabled on Holoiso. The Bluetooth situation shouldn't be related, I'm guessing the issue was found and resolved in the update.
> 
> P.S. No problem, we all start somewhere and it's the willingness to figure things out that gives us the experience we lack coming into something.

Thanks, I really appreciate. Hope you'll find out. I asked on reddit if someone has the issue on older versions of holoiso, not sure if anyone will reply, but I'll let you know.
Speaking of Home button, I noticed that sometimes, after pressing Home, the Start button is buggy, sometimes functions again. That's weird, and it seems to happen in different games. I don't know if it's related to holoiso or handygccs or anything else... And if it's the same on other devices.

**Comment by theVakhovskeIsTaken** [comment] 2022-12-13 22:11
> > > > > > > Thank you, the gamescope trick works.
> > > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > > 
> > > > > > 
> > > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > > ```
> > > > > > git clone
> > > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > > cd HandyGCCS
> > > > > > sudo make install
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > > 
> > > > 
> > > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > > 
> > > 
> > > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> > 
> > It means that the service is failing to start up on boot automatically.
> > 
> > I'm curious what does `sudo systemctl enable handycon.service` do for you?
> 
> The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)

https://www.reddit.com/r/holoiso/comments/zl595k/holoiso_is_now_running_over_kernel_609/?utm_medium=android_app&utm_source=share

the actual reason behind BT working

**Comment by doberman579** [comment] 2022-12-13 22:18
> update the binaries over Discovery

Really nice to talk to the developpers. I'd like to thank you for all the work you do, it's great.

**Comment by doberman579** [comment] 2022-12-13 22:20
> > > > > > > > Thank you, the gamescope trick works.
> > > > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > > > 
> > > > > > > 
> > > > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > > > ```
> > > > > > > git clone
> > > > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > > > cd HandyGCCS
> > > > > > > sudo make install
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > > > 
> > > > > 
> > > > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > > > 
> > > > 
> > > > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> > > 
> > > 
> > > It means that the service is failing to start up on boot automatically.
> > > I'm curious what does `sudo systemctl enable handycon.service` do for you?
> > 
> > 
> > The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)
> 
> https://www.reddit.com/r/holoiso/comments/zl595k/holoiso_is_now_running_over_kernel_609/?utm_medium=android_app&utm_source=share
> 
> the actual reason behind BT working

Really nice to talk to the developpers. I'd like to thank you for all the work you do, it's great.

**Comment by ruineka** [comment] 2022-12-14 14:14
> > > > > > > > > Thank you, the gamescope trick works.
> > > > > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > > > > ```
> > > > > > > > git clone
> > > > > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > > > > cd HandyGCCS
> > > > > > > > sudo make install
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > > > > 
> > > > > > 
> > > > > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > > > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > > > > 
> > > > > 
> > > > > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> > > > 
> > > > 
> > > > It means that the service is failing to start up on boot automatically.
> > > > I'm curious what does `sudo systemctl enable handycon.service` do for you?
> > > 
> > > 
> > > The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)
> > 
> > https://www.reddit.com/r/holoiso/comments/zl595k/holoiso_is_now_running_over_kernel_609/?utm_medium=android_app&utm_source=share
> > 
> > the actual reason behind BT working
> 
> Really nice to talk to the developpers. I'd like to thank you for all the work you do, it's great.

Can you delete the handygccs folder created by the commands and rerun? It'll pull some updated files and I want to make sure you have a clean environment to make install from.

**Comment by doberman579** [comment] 2022-12-14 17:36
> > > > > > > > > > Thank you, the gamescope trick works.
> > > > > > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > > > > > ```
> > > > > > > > > git clone
> > > > > > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > > > > > cd HandyGCCS
> > > > > > > > > sudo make install
> > > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > > > > > 
> > > > > > > 
> > > > > > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > > > > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > > > > > 
> > > > > > 
> > > > > > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> > > > > 
> > > > > 
> > > > > It means that the service is failing to start up on boot automatically.
> > > > > I'm curious what does `sudo systemctl enable handycon.service` do for you?
> > > > 
> > > > 
> > > > The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)
> > > 
> > > 
> > > https://www.reddit.com/r/holoiso/comments/zl595k/holoiso_is_now_running_over_kernel_609/?utm_medium=android_app&utm_source=share
> > > the actual reason behind BT working
> > 
> > 
> > Really nice to talk to the developpers. I'd like to thank you for all the work you do, it's great.
> 
> Can you delete the handygccs folder created by the commands and rerun? It'll pull some updated files and I want to make sure you have a clean environment to make install from.

I deleted the HandyGCCS folder, then did a fresh installation with the git clone command. Everything work til I reboot, then it doesn't work anymore. I alse retried systemctl start, it works but no more after reboot...

**Comment by doberman579** [comment] 2022-12-21 16:56
> > > > > > > > Thank you, the gamescope trick works.
> > > > > > > > But I have an issue on how to configure all the button functions, and to make the Bluetooth work properly. I cannot enable Bluetooth in the Configuration panel on Desktop mode, and I don't see it in Deck UI (or I didn't find it?). I could add Bluetooth device (in the right down corner of the desktop), but it never found any device around.
> > > > > > > > Are there any tricks to configure buttons and activate Bluetooth properly?
> > > > > > > 
> > > > > > > 
> > > > > > > I don't use Holoiso and instead actively work with ChimeraOS so I'm not familiar with the Bluetooth issue, but the Chimera team made a tool for all the buttons that can be easily used on Holoiso.
> > > > > > > go to desktop mode. Open the konsole and copy paste this
> > > > > > > ```
> > > > > > > git clone
> > > > > > > https://github.com/ShadowBlip/HandyGCCS.git
> > > > > > > cd HandyGCCS
> > > > > > > sudo make install
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Thank you for your contribution. I notice that every time I restart, I have to do the sudo make install t omake it work. Is there a way to make it last at every reboot?
> > > > > 
> > > > > 
> > > > > Thats unexpected behavior. It should be installing a service that handles the script. It almost sounds like it is failing to start it when rebooting.
> > > > > Can you try running 'sudo systemctl start handycon.service' and see if it starts it up without running the make install?
> > > > 
> > > > 
> > > > So I tried, the command `sudo systemctl start handycon.service` works when done, but doesn't work anymore when I reboot... I don't understand what it tells, but if it could help you understand the issue, I'll be glad
> > > 
> > > 
> > > It means that the service is failing to start up on boot automatically.
> > > I'm curious what does `sudo systemctl enable handycon.service` do for you?
> > 
> > 
> > The enable command also works, but the same, at reboot nothing works anymore. Just to tell, I did last holoISO update and now my Bluetooth functions. Could it be an interference between bluetooth and handycon? (I'm noob at that level, hope the question is not that stupid) I don't remember to have this issue before updating the system (but I did so many reinstall, chimeraOS, holoISO tests that I'm not sure anymore)
> 
> https://www.reddit.com/r/holoiso/comments/zl595k/holoiso_is_now_running_over_kernel_609/?utm_medium=android_app&utm_source=share
> 
> the actual reason behind BT working

So I have seen something weird. Whenb I used an external gamepad, when I press Steam button the menu comes, and Steam+A does the performance menu. But with HandyGCCS, it opens the performance menu with Steam button alone, and no way to have the main menu with Steam button. I don't know if something is different on OneXplayer 6800U, but HandyGCCS seeems to have an unusual functionning. I don't know if it is related to any of the previous issue I mentionned (unactivation at rebbot), but anyway it's weird...

**Comment by BluesBrothers7** [comment] 2023-03-09 11:58
Screen in beta version is still upside down.

**Comment by BluesBrothers7** [comment] 2023-03-16 09:57
I tried many different installers (holoiso-offline-installer (stable/beta/daily/etc.)). Does anybody know a version of the holloiso-Offline Installer in wich all the issues working proberly? (Screen in the right direction (upside up), Joycons working proberly, Updates are working, Holoiso boots).

Help is very much appreciated! Thank you!

**Comment by doberman579** [comment] 2023-03-16 11:21
> I tried many different installers (holoiso-offline-installer). Does anybody know a version of the holloiso-Offline Installer in wich all the issues working proberly? (Screen in the right direction (upside up), Joycons working proberly, Updates are working, Holosio boots).
> 
> Help is very much appreciated! Thank you!

I would be glad of a full solution, especially for system buttons (Home), because HandyGCCS is quite a pain to install. I also have always the infinite update bug, persisting with last holoiso-offline-installer. I know it's not that easy for people working on those issues, but it would be really great to have a solution for this.

**Comment by BluesBrothers7** [comment] 2023-03-16 11:44
In addition: Does anybody know  if the adressed issues (joycons, Screen rotation) made its way to upstream? e.g. screen rotation in different beta-versions is still upside down.

**Comment by doberman579** [comment] 2023-03-16 12:09
> In addition: Does anybody know if the adressed issues (joycons, Screen rotation) made its way to upstream? e.g. screen rotation in different beta-versions is still upside down.

In the regular version, my screen is alright with HoloISO on OXP Mini Pro

**Comment by BluesBrothers7** [comment] 2023-03-16 13:11
@doberman579 That ´s  true. But all the other issues still exitisting. :-) The update-issue and the boot issue are solved in beta but screen rotation isn´t.

**Comment by doberman579** [comment] 2023-03-17 16:10
@BluesBrothers7 I tried beta channel, but nothing changed in term of update, still the same bug

**Comment by BluesBrothers7** [comment] 2023-03-17 16:40
> @BluesBrothers7 I tried beta channel, but nothing changed in term of update, still the same bug

I refered to "beta-version" not beta channel. I can´t remember exactly where i downloaded this beta-version, but you can try one of these:
https://gdrivecdn.thevakhovske.pw/3:/daily_ci/

**Comment by doberman579** [comment] 2023-03-17 18:14
@BluesBrothers7 Thank you for the link. I guess I'm not gonna install the beta if the screen is upside down... But I'll wait for a better version to be out, thanks to the developers

**Closed as completed** 2023-09-08 08:02 UTC
