### ISSUE TITLE
Legacy support (Non uefi)

### ISSUE THREAD

**Issue by MZain3028** [holoiso-eol/holoiso#239] opened 2022-05-31 15:58 UTC
is there a possibilty to install Holo OS on legacy systems ?

**Comment by Grimish-ng** [comment] 2022-05-31 16:07
I'm just guessing here but I would assume no. Since most of the AMD and less so, nvidia stuff involved here is really only compatible on the hardware that as been available long after UEFI had become default/standard. I could be wrong. Maybe you got some nvida 9xx card that is legacy - which seems like a reach since I got hardware (nvidia 780) that has both legacy and UEFI. Not to mention this is being built from the official valve repository.

**Comment by MZain3028** [comment] 2022-05-31 19:59
> I'm just guessing here but I would assume no. Since most of the AMD and less so, nvidia stuff involved here is really only compatible on the hardware that as been available long after UEFI had become default/standard. I could be wrong. Maybe you got some nvida 9xx card that is legacy - which seems like a reach since I got hardware (nvidia 780) that has both legacy and UEFI. Not to mention this is being built from the official valve repository.

That's not the issue, I have an amd graphics card, I just have an old 1st gen xeon PC with legacy bios, no uefi bios support, and am unable to boot into the installer cause of that and was hoping there's a way to modify the installer or make a separate iso for older systems

**Comment by baodrate** [comment] 2022-06-02 14:43
Can't see any reason it couldn't be supported. ArchISO already supports Syslinux for BIOS booting (and the repo already contains `Syslinux/`. They just need to update the configuration files in there to match their changes to `efiboot/`, and add the appropriate options back to `bootmodes` in the `profiledef.sh`. Looking at the changes in here, I don't see any reason EFI booting is required.

**Comment by MZain3028** [comment] 2022-06-02 21:47
> Can't see any reason it couldn't be supported. ArchISO already supports Syslinux for BIOS booting (and the repo already contains `Syslinux/`. They just need to update the configuration files in there to match their changes to `efiboot/`, and add the appropriate options back to `bootmodes` in the `profiledef.sh`. Looking at the changes in here, I don't see any reason EFI booting is required.

**Comment by MZain3028** [comment] 2022-06-02 21:49
> Can't see any reason it couldn't be supported. ArchISO already supports Syslinux for BIOS booting (and the repo already contains `Syslinux/`. They just need to update the configuration files in there to match their changes to `efiboot/`, and add the appropriate options back to `bootmodes` in the `profiledef.sh`. Looking at the changes in here, I don't see any reason EFI booting is required.

Can you let me know what changes would be required to the conf files in efiboot/ ?

**Comment by baodrate** [comment] 2022-06-02 22:50
But if you're asking for BIOS support you'll want to *add* files to `syslinux/` not modifying anything in `efiboot/` (which stores the systemd-boot entries, which would only be relevant if you were booting from/installing to a UEFI system.

I'm not the best person to ask, but I would expect you can just translate the systemd-boot profiles in `efiboot/loader/entries/` from the [systemd-bootloader entry format](https://systemd.io/BOOT_LOADER_SPECIFICATION/) to the appropriate [syslinux config format](https://wiki.syslinux.org/wiki/index.php?title=Config). It seems pretty straight forward but you'd have to test it to make sure. 

You should be able to compare the files in this repo with the ones in `/usr/share/archiso/configs/releng/` (from the `archiso` package) to get an idea of what changes they've made.

**Comment by deftdawg** [comment] 2022-06-18 06:01
This is a dupe of #127

Though there's not really any technical reason it couldn't be made to work, non-UEFI systems are a comparative PITA to work with.

**Closed as completed** 2023-09-08 08:09 UTC
